# Generated by Django 4.0.6 on 2023-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rub_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
