version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data5/
    env_file:
      - ./.env
  web:
    build: 
      context: ../
      dockerfile: ./orders/Dockerfile
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/app/static/
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/static/
    restart: always
    depends_on:
      - web
volumes:
  static_value:
  postgres_data:
